workflows:
  android-workflow:
    name: Build Android App
    max_build_duration: 60
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64
      android:
        api_level: 34
    scripts:
      - name: Set up JDK
        script: |
          export PATH="$JAVA_HOME/bin:$PATH"
          java -version
      - name: Build with Gradle
        script: |
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
