workflows:
  android-workflow:
    name: Build Android App
    max_build_duration: 60
    environment:
      vars:
        JAVA_HOME: /opt/java/openjdk
        ANDROID_SDK_ROOT: /opt/android-sdk-linux
    scripts:
      - name: Set up JDK
        script: |
          export PATH="$JAVA_HOME/bin:$PATH"
          echo "JAVA_HOME is set to $JAVA_HOME"
          java -version
      - name: Build with Gradle
        script: |
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
