workflows:
  android-workflow:
    name: Build Android APK (no wrapper)
    max_build_duration: 60
    environment:
      vars:
        ANDROID_SDK_ROOT: /opt/android-sdk-linux
    scripts:
      - name: Install Gradle if needed
        script: |
          sudo apt-get update
          sudo apt-get install -y gradle
          gradle -v
      - name: Build APK
        script: |
          gradle assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
