workflows:
  android-workflow:
    name: Build Android App
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
    scripts:
      - name: Set up JDK
        script: |
          export PATH="$JAVA_HOME/bin:$PATH"
          java -version
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
